const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const typeInfo={story:{label:'Principal',color:'purple'},assignment:{label:'Encargo',color:'red'},optional:{label:'Opcional',color:'green'},event:{label:'Evento',color:'gray'}};
let all=[],byMonster=new Map(),mode='missions',category='',query='';const indexEl=document.getElementById('mission-index'),detailEl=document.getElementById('mission-detail'),searchEl=document.getElementById('mission-search'),categoryEl=document.getElementById('mission-categories');
function typeFor(x){return typeInfo[x.questType]||typeInfo.optional}function ticket(x,compact=false){const t=typeFor(x);return `<span class="quest-ticket-icon quest-ticket-icon--${t.color}${compact?' quest-ticket-icon--compact':''}" title="${esc(t.label)}"><span class="quest-ticket-icon__paper"></span><span class="quest-ticket-icon__seam"></span><span class="quest-ticket-icon__fold"></span></span>`}
function monsterIcons(x,interactive=false){const names=[...new Set(x.mainMonsters||[])];return names.length?`<span class="quest-monster-icons">${names.map(n=>{const m=byMonster.get(n);if(!m)return '';const img=`<img class="quest-monster-icon" src="${esc(m.image)}" alt="${esc(n)}" title="${esc(n)}" loading="lazy">`;return interactive?`<button type="button" class="quest-monster-icon-link" data-monster="${esc(n)}">${img}</button>`:img}).join('')}</span>`:''}
function filtered(){const term=norm(query);return all.filter(x=>x.model===mode&&(!category||x.boardGroup===category)&&(!term||norm([x.name,x.description,x.boardGroup,...(x.mainMonsters||[])].join(' ')).includes(term)))}
function renderCategories(){const cats=[...new Set(all.filter(x=>x.model===mode).map(x=>x.boardGroup).filter(Boolean))];if(!cats.includes(category))category='';categoryEl.innerHTML=`<div class="quests-subtoggle"><button type="button" class="quest-subfilter-btn${!category?' active':''}" data-category="">Todas</button>${cats.map(c=>`<button type="button" class="quest-subfilter-btn${c===category?' active':''}" data-category="${esc(c)}">${esc(c)}</button>`).join('')}</div>`;categoryEl.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;renderCategories();renderIndex()}));document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode))}
function renderIndex(){detailEl.hidden=true;indexEl.hidden=false;const rows=filtered();if(!rows.length){indexEl.innerHTML='<p class="no-data">No hay misiones que coincidan.</p>';return}const groups=new Map();for(const x of rows){const g=x.boardGroup||(mode==='missions'?'Historia':'Quests');if(!groups.has(g))groups.set(g,[]);groups.get(g).push(x)}indexEl.innerHTML=[...groups].map(([group,items])=>`<section class="decorations-slot-group"><h2 class="decorations-slot-heading">${esc(group)}</h2><div class="decorations-grid">${items.map(x=>`<button type="button" class="decoration-card quest-card" data-id="${esc(x.id)}">${ticket(x,true)}<span class="quest-card-copy"><span class="decoration-card-name">${esc(x.title||x.name)}</span><span class="quest-goal quest-goal--compact"><span>${esc(x.description||'—')}</span>${monsterIcons(x)}</span><span class="decoration-card-skill">${esc(typeFor(x).label)}</span></span></button>`).join('')}</div></section>`).join('');indexEl.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>showDetail(b.dataset.id)))}
function showDetail(id){const x=all.find(q=>q.id===id);if(!x)return;history.replaceState(null,'',`?q=${encodeURIComponent(id)}`);indexEl.hidden=true;detailEl.hidden=false;const t=typeFor(x);detailEl.innerHTML=`<button type="button" class="decorations-back" id="mission-back">← Volver a misiones</button><div class="decoration-detail-header">${ticket(x)}<h2>${esc(x.title||x.name)}</h2><span class="decoration-detail-slot">${esc(x.boardGroup||'')}</span></div><p class="quest-type-line"><span class="quest-type-badge quest-type-badge--${t.color}">${esc(t.label)}</span></p>${x.description?`<section class="block"><h3>Descripción</h3><p class="gs-material-intro">${esc(x.description)}</p></section>`:''}${(x.mainMonsters||[]).length?`<section class="block"><h3>Monstruos objetivo</h3><ul class="chips">${x.mainMonsters.map(n=>{const m=byMonster.get(n);return `<li class="chip quest-target-chip">${m?`<button type="button" class="skill-name-link quest-target-link" data-monster="${esc(n)}"><img class="quest-target-icon" src="${esc(m.image)}" alt="" loading="lazy">${esc(n)}</button>`:esc(n)}</li>`}).join('')}</ul></section>`:''}<a href="${esc(x.source)}" target="_blank" rel="noreferrer">Ver ficha completa en Kiranico ↗</a>`;detailEl.querySelector('#mission-back').addEventListener('click',()=>{history.replaceState(null,'',location.pathname);renderIndex()});detailEl.querySelectorAll('[data-monster]').forEach(b=>b.addEventListener('click',()=>location.href=`monster.html?m=${encodeURIComponent(b.dataset.monster)}`));window.scrollTo(0,0)}
async function init(){const [rows,large,small]=await Promise.all([fetch('data/missions.json').then(r=>r.json()),fetch('data/monsters.json').then(r=>r.json()),fetch('data/small_monsters.json').then(r=>r.json()).catch(()=>[])]);all=rows;byMonster=new Map(large.concat(small).map(m=>[m.name,m]));searchEl.addEventListener('input',()=>{query=searchEl.value;renderIndex()});document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;category='';renderCategories();renderIndex()}));renderCategories();const id=new URLSearchParams(location.search).get('q');if(id)showDetail(id);else renderIndex()}init().catch(()=>indexEl.innerHTML='<p class="no-data">No se pudieron cargar las misiones.</p>');
