const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm = s => String(s ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const categoryInfo = {
  village:{label:'Aldea',mode:'single'}, training:{label:'Entrenamiento',mode:'single'},
  hub_low:{label:'Sala de reuniones · Rango bajo',mode:'hub'}, hub_high:{label:'Sala de reuniones · Rango alto',mode:'hub'}, hub_master:{label:'Sala de reuniones · Rango maestro',mode:'hub'},
  event:{label:'Evento',mode:'hub'}, mystery:{label:'Investigación de anomalía',mode:'hub'}, follower:{label:'Misión con seguidor',mode:'hub'}, arena:{label:'Arena',mode:'hub'},
};
const typeInfo = {hunt:{label:'Caza',color:'red'},capture:{label:'Captura',color:'gray'},gather:{label:'Recolección',color:'green'},special:{label:'Especial',color:'purple'}};
let quests=[], monstersByName=new Map(), mode='single', category='', query='';
const indexEl=document.getElementById('quest-index'), detailEl=document.getElementById('quest-detail'), searchEl=document.getElementById('quest-search'), categoriesEl=document.getElementById('quest-categories');
function trMonster(name){return I18N?.monsterNames?.[name] || name;}
function modeFor(q){return categoryInfo[q.category]?.mode || 'hub';}
function labelFor(q){const base=categoryInfo[q.category]?.label || q.category;return q.stars ? `${base} ${q.category==='hub_master'?'M':''}${q.stars}★` : base;}
function typeFor(q){return typeInfo[q.questType] || typeInfo.special;}
function ticket(q, compact=false){const type=typeFor(q);return `<span class="quest-ticket-icon quest-ticket-icon--${type.color}${compact?' quest-ticket-icon--compact':''}" title="${esc(type.label)}"><span class="quest-ticket-icon__paper"></span><span class="quest-ticket-icon__seam"></span><span class="quest-ticket-icon__fold"></span></span>`;}
function monsterIcons(q, interactive=false){const names=[...new Set(q.mainMonsters||[])];if(!names.length)return '';return `<span class="quest-monster-icons">${names.map(name=>{const m=monstersByName.get(name);if(!m)return '';const img=`<img class="quest-monster-icon" src="${esc(m.image)}" alt="${esc(trMonster(name))}" title="${esc(trMonster(name))}" loading="lazy">`;return interactive?`<button class="quest-monster-icon-link" type="button" data-monster="${esc(name)}">${img}</button>`:img;}).join('')}</span>`;}
function stars(q, detail=false){if(!q.stars)return '';return `<span class="quest-stars${q.keyQuest?' quest-stars--key':''}${detail?' quest-stars--detail':''}"${q.keyQuest?' title="Misión clave"':''}>${q.category==='hub_master'?'M':''}${q.stars}★</span>`;}
function renderCategories(){const cats=[...new Set(quests.filter(q=>modeFor(q)===mode).map(q=>q.category))];if(!cats.includes(category))category='';categoriesEl.innerHTML=`<div class="quests-subtoggle"><button type="button" class="quest-subfilter-btn${!category?' active':''}" data-category="">Todas</button>${cats.map(c=>`<button type="button" class="quest-subfilter-btn${category===c?' active':''}" data-category="${c}">${esc(categoryInfo[c]?.label||c)}</button>`).join('')}</div>`;categoriesEl.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;renderCategories();renderIndex();}));document.querySelectorAll('[data-mode]').forEach(b=>{const active=b.dataset.mode===mode;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));});}
function filtered(){const term=norm(query);return quests.filter(q=>modeFor(q)===mode&&(!category||q.category===category)&&(!term||norm([q.nameEs,q.nameEn,q.goalCondition,q.client,q.location,...(q.mainMonsters||[])].join(' ')).includes(term)));}
function renderIndex(){detailEl.hidden=true;indexEl.hidden=false;const rows=filtered();if(!rows.length){indexEl.innerHTML='<p class="no-data">No hay misiones que coincidan.</p>';return;}const groups=new Map();for(const q of rows){const label=labelFor(q);if(!groups.has(label))groups.set(label,[]);groups.get(label).push(q);}indexEl.innerHTML=[...groups].map(([label,group])=>`<section class="decorations-slot-group"><h2 class="decorations-slot-heading">${esc(label)}</h2><div class="decorations-grid">${group.sort((a,b)=>Number(b.keyQuest)-Number(a.keyQuest)||String(a.nameEs).localeCompare(String(b.nameEs),'es')).map(q=>`<button type="button" class="decoration-card quest-card" data-quest="${q.id}">${ticket(q,true)}<span class="quest-card-copy"><span class="decoration-card-name">${esc(q.nameEs.replace(/^\d+★\s*/,''))}</span><span class="quest-goal quest-goal--compact"><span>${esc(q.goalCondition||'—')}</span>${monsterIcons(q)}</span><span class="decoration-card-skill">${stars(q)} ${esc(typeFor(q).label)} · ${esc(q.client? q.client.split(':')[0]:'—')}</span></span></button>`).join('')}</div></section>`).join('');indexEl.querySelectorAll('[data-quest]').forEach(b=>b.addEventListener('click',()=>showDetail(b.dataset.quest)));}
function showDetail(id){const q=quests.find(x=>x.id===id);if(!q)return;history.replaceState(null,'',`?q=${encodeURIComponent(id)}`);indexEl.hidden=true;detailEl.hidden=false;const type=typeFor(q);detailEl.innerHTML=`<button type="button" class="decorations-back" id="quest-back">← Volver a misiones</button><div class="decoration-detail-header">${ticket(q)}<h2>${esc(q.nameEs.replace(/^\d+★\s*/,''))}</h2><span class="decoration-detail-slot">${esc(labelFor(q))}</span></div><p class="quest-type-line"><span class="quest-type-badge quest-type-badge--${type.color}">${esc(type.label)}</span>${stars(q,true)}</p><p class="gs-material-intro"><strong>Cliente:</strong> ${esc(q.client||'—')}</p><p class="gs-material-intro"><strong>Ubicación:</strong> ${esc(q.location||'—')}</p><p class="gs-material-intro quest-goal-detail"><span><strong>Objetivo:</strong> ${esc(q.goalCondition||'—')}</span>${monsterIcons(q,true)}</p><p class="gs-material-intro"><strong>Condiciones de fracaso:</strong> ${esc(q.failureConditions||'—')}</p>${(q.mainMonsters||[]).length?`<section class="block"><h3>Monstruos objetivo</h3><ul class="chips">${q.mainMonsters.map(name=>{const m=monstersByName.get(name);return `<li class="chip quest-target-chip">${m?`<button type="button" class="skill-name-link quest-target-link" data-monster="${esc(name)}"><img class="quest-target-icon" src="${esc(m.image)}" alt="" loading="lazy">${esc(trMonster(name))}</button>`:esc(trMonster(name))}</li>`;}).join('')}</ul></section>`:''}<section class="block"><h3>Detalles</h3><p class="gs-material-intro">${esc(q.client||'')}</p><a href="${esc(q.detailSource)}" target="_blank" rel="noreferrer">Ver ficha completa en Kiranico ↗</a></section>`;detailEl.querySelector('#quest-back').addEventListener('click',()=>{history.replaceState(null,'',location.pathname);renderIndex();});detailEl.querySelectorAll('[data-monster]').forEach(b=>b.addEventListener('click',()=>location.href=`monster.html?m=${encodeURIComponent(b.dataset.monster)}`));window.scrollTo(0,0);}
async function init(){const [qs,large,small]=await Promise.all([fetch('data/quests.json').then(r=>r.json()),fetch('data/monsters.json').then(r=>r.json()),fetch('data/small_monsters.json').then(r=>r.json())]);quests=qs;monstersByName=new Map(large.concat(small).map(m=>[m.name,m]));searchEl.addEventListener('input',()=>{query=searchEl.value;renderIndex();});document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;category='';renderCategories();renderIndex();}));renderCategories();const id=new URLSearchParams(location.search).get('q');if(id)showDetail(id);else renderIndex();}
init().catch(()=>{indexEl.innerHTML='<p class="no-data">No se pudieron cargar las misiones.</p>';});
